### PR TITLE
Fix out step not responding with version data

### LINKED ISSUE #44: Resource produces duplicate Concourse versions for the same blob
Hi there :wave: I'm not entirely sure if this is known/expected behaviour and someone can correct my usage of the resource or if this actually a bug, but I've noticed that the `azure-blobstore-resource` seems to be producing duplicate Concourse resource versions for the same blob. This is an issue for me because some of my jobs are set up to `trigger: true` on new blob versions, but sometimes they get stuck looking for the newest versions that satisfy my `passed` criteria and don't trigger as expected.

In my pipeline I take in a blob from another source and `put` it to an Azure blobstore container via the resource to keep a copy of the blob I can manage myself instead of relying on the original source to be available. Later on in the same pipeline I `get` the blob using the same `azure-blobstore-resource` instance I `put`ted to earlier and do some work with it. When I look at the versions produced by the `azure-blobstore-resource` I can see 2 resource versions for the same blob:

image

One has just the `path` field and the other has `path` and `version`. Both of the `path`s are the same and refer to the same blob, but it looks like because the second resource version has the additional `version` field Concourse treats them as 2 separate resource versions.

I had a quick look over the implementation and it looks like in the `out` script it produces new Concourse resource versions with just the `path` field (I'm using regexes, not blobstore snapshots):

https://github.com/pivotal-cf/azure-blobstore-resource/blob/0b0c7277cf6b0a9ca3bf04398793ae49d3c8f8b5/cmd/out/main.go#L80-L84

but the `check` script produces new Concourse resource versions with a `path` and a `version`:

https://github.com/pivotal-cf/azure-blobstore-resource/blob/0b0c7277cf6b0a9ca3bf04398793ae49d3c8f8b5/api/check.go#L152-L156

Unless I'm not using the resource correctly, I would expect to see only 1 resource version for a given blob.

### PR DESCRIPTION
**Pull request by crusstu**
I took a stab at fixing #44, but would definitely appreciate feedback.

Design-wise I wasn't sure if the logic to pull out the version from the blob name should be turned into its own function and if so where it should live. The implementation in `check` loops over all the blobs in the selected blobstore and does some other interleaved work so I'm not sure if the two callsites can have the common logic extracted.

Closes #44.

### CODE REVIEW

File: cmd/out/main.go [hunk 1]
```diff
@@ -49,6 +53,27 @@ func main() {
...
 		blobBaseName := filepath.Base(outRequest.Params.File)
 		blobName = filepath.Join(blobPath, blobBaseName)
+
+		matcher, err := regexp.Compile(outRequest.Source.Regexp)
+		if err != nil {
+			log.Fatal("failed to compile source configuration regex: ", err)
+		}
+
+		matches := matcher.FindStringSubmatch(blobName)
+		if len(matches) >= 2 {
```
Comment (crusstu) [inline cmd/out/main.go:63]: I wasn't sure if `len(matches) < 2` if the regex doesn't match anything in the blob name should be a fatal error, or if this implementation was sufficient.

Comment (christianang) [reply cmd/out/main.go:63]: I think not failing here is okay. If it causes unforeseen issues to not explicitly error we can add it in later, but I don't expect this to happen. It also keeps old behavior (i.e didn't use to error if the regex didn't find a match), so in that regard it may also be valuable.

File: cmd/out/main.go [hunk 2]
```diff
@@ -49,6 +53,27 @@ func main() {
 		blobPath := filepath.Dir(outRequest.Source.Regexp)
 		blobBaseName := filepath.Base(outRequest.Params.File)
 		blobName = filepath.Join(blobPath, blobBaseName)
+
+		matcher, err := regexp.Compile(outRequest.Source.Regexp)
+		if err != nil {
+			log.Fatal("failed to compile source configuration regex: ", err)
+		}
+
+		matches := matcher.FindStringSubmatch(blobName)
```
Comment (christianang) [inline cmd/out/main.go:62]: The `blobName` pulls from the params and isn't the actual path, which has the version in it. I think this code needs to move lower down to after the `out.UploadFileToBlobstore` call and matches on the `path`.

Noticed this by running the `./acceptance` tests. Specifically [this test](https://github.com/pivotal-cf/azure-blobstore-resource/blob/master/acceptance/out_test.go#L149) if you'd like one to focus. Unfortunately don't have GitHub PR actions to run the tests so you'll have to run this locally. It should be fairly straight forward though, you will need a storage account name and the storage account key the tests can use to upload/download files to/from Azure. More info [here](https://github.com/pivotal-cf/azure-blobstore-resource/blob/master/acceptance/README.md). Happy to answer any questions if you get stuck.

**Review by christianang — CHANGES_REQUESTED** [review]

**Comment by christianang** [comment]
Thanks for putting the work into this PR! I tried this locally and ran into an issue, once the above is fixed and I've tested that the change works I think it can be merged.

re: design question. I think your design decisions made sense. I'm fine with the duplication and if it occurs in more places after this we can reconsider if it should be abstracted.

Feel free to ask questions here if you have any trouble. Thanks!

File: cmd/out/main.go (hunk 2 above)
Comment (crusstu) [reply cmd/out/main.go:62]: Thanks for the feedback, Christian! I'd taken a look at the unit tests but completely missed the `./acceptance` directory, I'll have a look at enhancing the test cases to make sure we check for the version on the output and get this fixed up.

**Comment by crusstu** [comment]
Hey @christianang, thanks again for the feedback; I think I've addressed the points you raised.

I see what you mean about `blobName`, so I moved the version extraction logic to operate on the `path` returned by the blob upload instead.

I also added a test for the version number and was able to validate it with the `./acceptance` tests, so we should be good on the tests front.

Let me know if there's anything I've missed!

**Comment by christianang** [comment]
Looks great! Merged, once it makes it through CI I'll cut a new release.

**Comment by christianang** [comment]
New release has been cut: https://github.com/pivotal-cf/azure-blobstore-resource/releases/tag/v0.13.0
